<Project Sdk="Microsoft.NET.Sdk.Razor">
	<ItemGroup>
		<!-- Fix for: https://github.com/bUnit-dev/bUnit/issues/1872 -->
		<PackageReference Include="AngleSharp" Version="*" />
		<PackageReference Include="bunit" Version="*" />
		<ProjectReference Include="..\..\src\Hosting.Web.Components\Hosting.Web.Components.csproj" />
	</ItemGroup>
</Project>
