<Project>
	<PropertyGroup>
		<!-- MTP requires an executable test host. -->
		<OutputType>Exe</OutputType>
		<_ParentTargets>$([MSBuild]::GetPathOfFileAbove('Directory.Build.targets', '$(MSBuildThisFileDirectory)../'))</_ParentTargets>
	</PropertyGroup>
	<Import Project="$(_ParentTargets)" Condition="Exists('$(_ParentTargets)')" />
</Project>
