<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
	</PropertyGroup>

	<ItemGroup>
		<NorseRef Include="DesignSystem.Stories">
			<Repo>Bragi</Repo>
		</NorseRef>
		<NorseRef Include="Infrastructure.Components.Theme.FluentUI">
			<Repo>Midgard</Repo>
		</NorseRef>
		<PackageReference Include="BlazingStory" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all" />

	</ItemGroup>

</Project>
