<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="11.*-*" />
		<PackageReference Include="Microsoft.Playwright" Version="*" />
		<ProjectReference Include="..\..\src\Hosting.Stories\Hosting.Stories.csproj" />
		<Compile Include="../BrowserTesting/*.cs" Link="BrowserTesting/%(Filename)%(Extension)" />
	</ItemGroup>
</Project>
