<Project Sdk="Microsoft.NET.Sdk.Worker">
	<PropertyGroup>
		<ContainerBaseImage>mcr.microsoft.com/dotnet/runtime:$(ContainerVersion)</ContainerBaseImage>
	</PropertyGroup>
	<ItemGroup>
		<NorseRef Include="Infrastructure.ServiceDefaults">
			<Repo>Midgard</Repo>
		</NorseRef>
		<PackageReference Include="Microsoft.Extensions.Hosting" />
	</ItemGroup>
</Project>
