name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write
  pull-requests: write
  security-events: write

jobs:
  release:
    uses: NorseArchitecture/.github/.github/workflows/release-container.yml@master
    secrets: inherit
